trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'catalog/**'
      - 'shell/**'
      - 'azure-pipelines.yml'

pool:
  vmImage: ubuntu-latest

variables:
  - group: static-web-apps-tokens  # Variable group containing deployment tokens

jobs:
  - job: deploy_catalog
    displayName: 'Deploy Catalog App'
    steps:
      - checkout: self
        submodules: true
      
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Setup Node.js 20.x'
      
      - script: |
          cd catalog
          npm ci
        displayName: 'Install dependencies for Catalog'
      
      - script: |
          cd catalog
          npm run build
        displayName: 'Build Catalog App'
      
      - task: AzureStaticWebApp@0
        displayName: 'Deploy Catalog to Azure Static Web App'
        inputs:
          app_location: '/catalog'
          api_location: ''
          output_location: 'dist'
          azure_static_web_apps_api_token: $(CATALOG_DEPLOYMENT_TOKEN)
          workingDirectory: $(System.DefaultWorkingDirectory)

  - job: deploy_shell
    displayName: 'Deploy Shell App'
    dependsOn: deploy_catalog  # Makes sure catalog is deployed first
    steps:
      - checkout: self
        submodules: true
      
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Setup Node.js 20.x'
      
      - script: |
          cd shell
          npm ci
        displayName: 'Install dependencies for Shell'
      
      - script: |
          cd shell
          npm run build
        displayName: 'Build Shell App'
        env:
          VITE_CATALOG_URL: $(CATALOG_URL)  # URL to the catalog's remoteEntry.js
      
      - task: AzureStaticWebApp@0
        displayName: 'Deploy Shell to Azure Static Web App'
        inputs:
          app_location: '/shell'
          api_location: ''
          output_location: 'dist'
          azure_static_web_apps_api_token: $(SHELL_DEPLOYMENT_TOKEN)
          workingDirectory: $(System.DefaultWorkingDirectory)
